### ISSUE TITLE
Classification labels should be in [0 to 538580]

### ISSUE THREAD

**Issue by Kiran-G1** [Kiran-G1/LogisticRegression#2]
```
Exception in thread "main" org.apache.spark.SparkException: Classification labels should be in [0 to 538580]. Found 9458610 invalid labels.
	at org.apache.spark.ml.classification.LogisticRegression.train(LogisticRegression.scala:563)
	at org.apache.spark.ml.classification.LogisticRegression.train(LogisticRegression.scala:487)
	at org.apache.spark.ml.classification.LogisticRegression.train(LogisticRegression.scala:278)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at com.kamali.exe.TaxiLogistic$.main(TaxiLogistic.scala:127)
	at com.kamali.exe.TaxiLogistic.main(TaxiLogistic.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
``
```

**Comment by Kiran-G1** [comment]
think the problem is not with the no.of labels.
```

18/07/04 22:07:14 ERROR LogisticRegression: Classification labels should be in [0 to 111]. Found 978 invalid labels.
Exception in thread "main" org.apache.spark.SparkException: Classification labels should be in [0 to 111]. Found 978 invalid labels.

```

**Comment by Kiran-G1** [comment]
```18/07/04 22:07:14 ERROR LogisticRegression: Classification labels should be in [0 to 111]. Found 978 invalid labels.Exception in thread "main" org.apache.spark.SparkException: Classification labels should be in [0 to 111]. Found 978 invalid labels.
